### ISSUE TITLE
unexpected token ??

### ISSUE THREAD

**Issue by GlennNg** [HexM7/declus#2]
Hello!

I'm new to this. but i'm getting unexpected token when i tried your example.

```
ctx.drawImage(
          frames[i],
          baseLayer.marginLeft ?? 0,
          baseLayer.marginTop ?? 0,
          baseLayer.width ?? width,
          baseLayer.height ?? height,
        );
```

Error seems to be from the index file of the package. What's the "??" in the declaration here?

**Comment by zignis** [comment]
"`??`" is a **nullish coalescing** operator, which is currently just a proposal at the moment. Issue has been fixed by replacing them with `or` (`||`) operator. https://github.com/HexM7/declus/commit/3a5d9146ed4073e700163c5f8030be595be1648d
